Adds capability to remember recent hosts.
rosjava/android_core pull request #263
Opened 2017-04-04 22:54 UTC by stratomda

Adds capability to remember recent hosts. When entering the Master URI a list of recent Master URIs is presented. This implements the Remember recent hosts task in rosjava/android_core#257.
- [X] Remember recent hosts (useful when changing masters)

2017-04-05 13:03 UTC, adamantivm requested changes
Great contribution @stratomda !! I left only a few minor style / name nits if you could please address.

2017-04-05 13:03 UTC, adamantivm commented on android_10/src/org/ros/android/MasterChooser.java
> +   * Stores the recent Master URI to preferences. This implementation does not use
nit: rewording. Perhaps something like: "adds the given URI to the list of recent Master URIs shared preferences". And perhaps the method name should be `addRecentMasterURI` instead.

2017-04-05 13:03 UTC, adamantivm commented on android_10/src/org/ros/android/MasterChooser.java
> +  private void setRecentMasterURI(String uri)  {
please review formatting. For example: open should go on the same line as the control statement with one blank space (not zero, not two), etc.
Hint: it is possible to configure Android Studio to do this for you.

2017-04-05 13:03 UTC, adamantivm commented on android_10/src/org/ros/android/MasterChooser.java
> +    for(int i=0; i<recentURIs.size(); i++)
i.e.: here, bring open brace to the line with for

2017-04-05 13:33 UTC, jubeira commented
The code is looking good @stratomda !
Apart from the nits that @adamantivm pointed out, I would leave a space after statements like `for`, `if`, etc. so as to match the general coding style of rosjava.
In summary:
- Braces in the same line of statements, with one space after the end of the control statement.
- Parenthesis with one space after the control statements.

I haven't tried the changes in an app yet, I will do soon when I have some time. Thanks again for your work!

2017-04-06 02:31 UTC, stratomda commented
Sorry about those formatting issues. I'll make sure to follow those on the next commit!

2017-04-06 13:50 UTC, adamantivm approved these changes
@stratomda thanks for the updates. I included a few more formatting / minor naming change requests.
Another question too: how would the user delete recent URIs? I would be OK with merging without having that ability, but then I'd appreciate creating an issue to remind us to add that capability somehow later.

2017-04-06 13:50 UTC, adamantivm commented on android_10/src/org/ros/android/MasterChooser.java
> +  private void setRecentMasterURI(String uri) {
how about renaming this to `addRecentMaterURI` ?

2017-04-06 13:50 UTC, adamantivm commented on android_10/src/org/ros/android/MasterChooser.java
> +    if(!recentURIs.contains(uri)) {
Another formatting nit: space between `if` and open parenthesis (and `for`, etc.).

2017-04-06 14:39 UTC, stratomda commented on android_10/src/org/ros/android/MasterChooser.java
> +  private void setRecentMasterURI(String uri) {
Agree with you. Forgot to add in latest commit.

2017-04-06 14:39 UTC, stratomda commented on android_10/src/org/ros/android/MasterChooser.java
> +    if(!recentURIs.contains(uri)) {
I'll address this. Didn't see it.

2017-04-06 14:40 UTC, stratomda commented
Lets create an issue and we can hopefully add an option to the MasterChooserSettings to clear recent Master URIs. Does that sound like a plan? Otherwise in advanced options I could add an option to remove them as well.

2017-04-06 15:14 UTC, adamantivm commented
@stratomda I would be perfectly OK with your proposal of an issue. Would you mind going ahead and creating it? Or alternatively updating the issue you and @jubeira have been using to track desired updates to the Master Chooser. Either would be fine.

2017-04-06 20:49 UTC, merged